sudo: false
language: go
go:
  - 1.4.1
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - PATH=$PATH:$HOME/gopath/bin
  - go get -v -t ./...
script:
  - go tool vet -composites=false $(ls -d */ | grep -v Godeps)
  - ginkgo -p -r -race -failOnPending -randomizeAllSpecs
branches:
  only:
  - master
